import type { Category, Product } from './types'

export const categories: Category[] = [
  { name: 'Electronics', icon: '📱', image: 'https://images.pexels.com/photos/3945679/pexels-photo-3945679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Mobiles', icon: '📱', image: 'https://images.pexels.com/photos/3945698/pexels-photo-3945698.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Laptops', icon: '💻', image: 'https://images.pexels.com/photos/8533587/pexels-photo-8533587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Fashion', icon: '👗', image: 'https://images.pexels.com/photos/8306365/pexels-photo-8306365.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: "Women's Fashion", icon: '👚', image: 'https://images.pexels.com/photos/8619007/pexels-photo-8619007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: "Men's Fashion", icon: '👔', image: 'https://images.pexels.com/photos/9775889/pexels-photo-9775889.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Shoes', icon: '👟', image: 'https://images.pexels.com/photos/1456733/pexels-photo-1456733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Beauty', icon: '💄', image: 'https://images.pexels.com/photos/1625037/pexels-photo-1625037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Accessories', icon: '👜', image: 'https://images.pexels.com/photos/14806252/pexels-photo-14806252.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Home & Kitchen', icon: '🏠', image: 'https://images.pexels.com/photos/30946801/pexels-photo-30946801.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Furniture', icon: '🪑', image: 'https://images.pexels.com/photos/2766975/pexels-photo-2766975.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Books', icon: '📚', image: 'https://images.pexels.com/photos/433333/pexels-photo-433333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Sports & Fitness', icon: '🏋️', image: 'https://images.pexels.com/photos/19025674/pexels-photo-19025674.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Grocery', icon: '🛒', image: 'https://images.pexels.com/photos/7129143/pexels-photo-7129143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Toys', icon: '🧸', image: 'https://images.pexels.com/photos/14007163/pexels-photo-14007163.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
  { name: 'Travel', icon: '🧳', image: 'https://images.pexels.com/photos/27945494/pexels-photo-27945494.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
]

const img = (url: string) => url

export const products: Product[] = [
  // Electronics
  {
    id: 1,
    name: 'Galaxy Pro Smartphone 5G',
    category: 'Electronics',
    subcategory: 'Mobiles',
    price: 24999,
    oldPrice: 34999,
    rating: 4.5,
    reviews: 2341,
    image: img('https://images.pexels.com/photos/3945679/pexels-photo-3945679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/3945679/pexels-photo-3945679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/3945698/pexels-photo-3945698.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Experience blazing-fast 5G connectivity with a stunning AMOLED display, triple camera system, and all-day battery life. The Galaxy Pro is built for those who demand the best.',
    features: ['6.7" AMOLED 120Hz Display', 'Triple 64MP Camera System', '5000mAh Battery', '5G Connectivity', '8GB RAM / 256GB Storage'],
    badge: 'Best Seller',
  },
  {
    id: 2,
    name: 'UltraBook Pro 14 Laptop',
    category: 'Electronics',
    subcategory: 'Laptops',
    price: 59999,
    oldPrice: 79999,
    rating: 4.6,
    reviews: 1820,
    image: img('https://images.pexels.com/photos/8533587/pexels-photo-8533587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/8533587/pexels-photo-8533587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/6968164/pexels-photo-6968164.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Ultra-thin and powerful laptop with the latest processor, stunning Retina display, and up to 18 hours of battery life. Perfect for work and play.',
    features: ['14" Retina Display', '16GB Unified Memory', '512GB SSD', 'Up to 18 hours battery', 'Backlit Keyboard'],
    badge: 'Premium',
  },
  {
    id: 3,
    name: 'Wireless Noise-Cancelling Headphones',
    category: 'Electronics',
    subcategory: 'Electronics',
    price: 4999,
    oldPrice: 8999,
    rating: 4.5,
    reviews: 3120,
    image: img('https://images.pexels.com/photos/7772548/pexels-photo-7772548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/7772548/pexels-photo-7772548.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Immerse yourself in pure sound with active noise cancellation, 40-hour battery life, and ultra-comfortable ear cushions. Your perfect audio companion.',
    features: ['Active Noise Cancellation', '40-hour Battery Life', 'Bluetooth 5.3', 'Fast Charge', 'Foldable Design'],
    badge: 'Deal',
  },
  {
    id: 4,
    name: 'Portable Bluetooth Speaker',
    category: 'Electronics',
    subcategory: 'Electronics',
    price: 1799,
    oldPrice: 2999,
    rating: 4.4,
    reviews: 4520,
    image: img('https://images.pexels.com/photos/4917455/pexels-photo-4917455.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/4917455/pexels-photo-4917455.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Powerful, compact Bluetooth speaker with deep bass, waterproof design, and 12-hour playtime. Take your music anywhere.',
    features: ['IPX7 Waterproof', '12-hour Battery', 'Deep Bass Technology', 'Bluetooth 5.0', 'Built-in Mic'],
  },
  {
    id: 5,
    name: 'Smart Watch Fitness Tracker',
    category: 'Electronics',
    subcategory: 'Electronics',
    price: 3999,
    oldPrice: 5999,
    rating: 4.4,
    reviews: 2890,
    image: img('https://images.pexels.com/photos/267391/pexels-photo-267391.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/267391/pexels-photo-267391.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/5081914/pexels-photo-5081914.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Track your fitness goals with heart rate monitoring, sleep tracking, GPS, and 100+ sport modes. Stay connected with smart notifications.',
    features: ['Heart Rate Monitor', 'Sleep Tracking', 'Built-in GPS', '100+ Sport Modes', '7-day Battery Life'],
    badge: 'Trending',
  },
  {
    id: 6,
    name: '10" Tablet with Stylus',
    category: 'Electronics',
    subcategory: 'Electronics',
    price: 18999,
    oldPrice: 24999,
    rating: 4.3,
    reviews: 1240,
    image: img('https://images.pexels.com/photos/10535365/pexels-photo-10535365.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/10535365/pexels-photo-10535365.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/341523/pexels-photo-341523.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'A versatile 10-inch tablet with included stylus, perfect for drawing, note-taking, and entertainment. Stunning display with vivid colors.',
    features: ['10" Full HD Display', 'Included Stylus Pen', '128GB Storage', '12-hour Battery', 'Quad Speakers'],
  },
  {
    id: 7,
    name: 'Mirrorless Camera 4K',
    category: 'Electronics',
    subcategory: 'Electronics',
    price: 74999,
    oldPrice: 89999,
    rating: 4.7,
    reviews: 890,
    image: img('https://images.pexels.com/photos/17801168/pexels-photo-17801168.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/17801168/pexels-photo-17801168.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37585377/pexels-photo-37585377.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Professional-grade mirrorless camera with 4K video recording, 24MP sensor, and interchangeable lens system. Capture every detail.',
    features: ['24MP APS-C Sensor', '4K Video Recording', '5-axis Stabilization', 'Wi-Fi & Bluetooth', 'Weather Sealed'],
    badge: 'Premium',
  },
  {
    id: 8,
    name: 'Budget Smartphone 4G',
    category: 'Electronics',
    subcategory: 'Mobiles',
    price: 9999,
    oldPrice: 14999,
    rating: 4.2,
    reviews: 5670,
    image: img('https://images.pexels.com/photos/3945698/pexels-photo-3945698.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/3945698/pexels-photo-3945698.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Affordable smartphone with a large display, dual camera, and long-lasting battery. Great value for everyday use.',
    features: ['6.5" HD+ Display', 'Dual 13MP Camera', '4000mAh Battery', '4GB RAM / 64GB Storage', 'Face Unlock'],
    badge: 'Value',
  },

  // Fashion - Women
  {
    id: 9,
    name: 'Floral Summer Dress',
    category: "Women's Fashion",
    subcategory: 'Fashion',
    price: 1299,
    oldPrice: 2999,
    rating: 4.6,
    reviews: 1890,
    image: img('https://images.pexels.com/photos/8386647/pexels-photo-8386647.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/8386647/pexels-photo-8386647.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8619007/pexels-photo-8619007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Light and breezy floral dress perfect for summer outings. Made from soft, breathable cotton fabric with a flattering fit.',
    features: ['100% Cotton', 'Machine Washable', 'Knee Length', 'Floral Print', 'Available in 3 Colors'],
    badge: 'Best Seller',
  },
  {
    id: 10,
    name: 'Elegant Silk Saree',
    category: "Women's Fashion",
    subcategory: 'Fashion',
    price: 2499,
    oldPrice: 4999,
    rating: 4.7,
    reviews: 2340,
    image: img('https://images.pexels.com/photos/36041239/pexels-photo-36041239.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/36041239/pexels-photo-36041239.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/14928074/pexels-photo-14928074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Beautiful traditional silk saree with intricate zari work. Perfect for weddings, festivals, and special occasions.',
    features: ['Pure Silk', 'Zari Border Work', 'Includes Blouse Piece', 'Dry Clean Only', 'Traditional Design'],
    badge: 'Festive Special',
  },
  {
    id: 11,
    name: 'Designer Party Saree',
    category: "Women's Fashion",
    subcategory: 'Fashion',
    price: 3299,
    oldPrice: 5999,
    rating: 4.5,
    reviews: 1560,
    image: img('https://images.pexels.com/photos/14928074/pexels-photo-14928074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/14928074/pexels-photo-14928074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Stunning designer saree with elegant embroidery and rich colors. Make a statement at your next celebration.',
    features: ['Designer Wear', 'Heavy Embroidery', 'Includes Blouse Piece', 'Premium Fabric', 'Festive Collection'],
  },
  {
    id: 12,
    name: 'Blue Cotton Saree',
    category: "Women's Fashion",
    subcategory: 'Fashion',
    price: 1799,
    oldPrice: 2999,
    rating: 4.4,
    reviews: 980,
    image: img('https://images.pexels.com/photos/7693907/pexels-photo-7693907.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/7693907/pexels-photo-7693907.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Comfortable cotton saree in beautiful blue shade. Perfect for daily wear and office use.',
    features: ['Pure Cotton', 'Comfortable Fit', 'Daily Wear', 'Lightweight', 'Easy to Drape'],
  },

  // Fashion - Men
  {
    id: 13,
    name: 'Premium Cotton T-Shirt',
    category: "Men's Fashion",
    subcategory: 'Fashion',
    price: 599,
    oldPrice: 1299,
    rating: 4.3,
    reviews: 3400,
    image: img('https://images.pexels.com/photos/9775889/pexels-photo-9775889.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/9775889/pexels-photo-9775889.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36942017/pexels-photo-36942017.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Soft, breathable cotton t-shirt with a modern fit. A versatile essential for your everyday wardrobe.',
    features: ['100% Premium Cotton', 'Regular Fit', 'Machine Washable', 'Soft Fabric', 'Multiple Colors'],
    badge: 'Deal',
  },
  {
    id: 14,
    name: 'Graphic Print T-Shirt',
    category: "Men's Fashion",
    subcategory: 'Fashion',
    price: 699,
    oldPrice: 1499,
    rating: 4.4,
    reviews: 2100,
    image: img('https://images.pexels.com/photos/15258903/pexels-photo-15258903.png?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/15258903/pexels-photo-15258903.png?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Trendy oversized graphic t-shirt with artistic print. Make a bold style statement.',
    features: ['Oversized Fit', 'Graphic Print', 'Cotton Blend', 'Streetwear Style', 'Pre-shrunk'],
    badge: 'Trending',
  },
  {
    id: 15,
    name: 'Slim Fit Denim Jeans',
    category: "Men's Fashion",
    subcategory: 'Fashion',
    price: 1299,
    oldPrice: 2499,
    rating: 4.5,
    reviews: 4500,
    image: img('https://images.pexels.com/photos/10133274/pexels-photo-10133274.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/10133274/pexels-photo-10133274.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/1082526/pexels-photo-1082526.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Classic slim-fit denim jeans with stretch comfort. Durable, stylish, and perfect for any occasion.',
    features: ['Slim Fit', 'Stretch Denim', '5-Pocket Style', 'Machine Washable', 'Available in 4 Shades'],
    badge: 'Best Seller',
  },
  {
    id: 16,
    name: 'Classic Leather Jacket',
    category: "Men's Fashion",
    subcategory: 'Fashion',
    price: 3999,
    oldPrice: 6999,
    rating: 4.6,
    reviews: 1230,
    image: img('https://images.pexels.com/photos/31696292/pexels-photo-31696292.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/31696292/pexels-photo-31696292.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/1833077/pexels-photo-1833077.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Premium genuine leather jacket with a timeless design. A wardrobe investment that never goes out of style.',
    features: ['Genuine Leather', 'Inner Lining', 'Zip Closure', 'Multiple Pockets', 'Classic Design'],
    badge: 'Premium',
  },
  {
    id: 17,
    name: 'Modern Casual Shirt',
    category: "Men's Fashion",
    subcategory: 'Fashion',
    price: 899,
    oldPrice: 1799,
    rating: 4.2,
    reviews: 1670,
    image: img('https://images.pexels.com/photos/2421356/pexels-photo-2421356.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/2421356/pexels-photo-2421356.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/12803209/pexels-photo-12803209.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Stylish casual shirt with a modern fit. Perfect for both work and weekend wear.',
    features: ['Cotton Blend', 'Modern Fit', 'Button-down Collar', 'Machine Washable', 'Breathable Fabric'],
  },

  // Shoes
  {
    id: 18,
    name: 'Running Shoes Pro',
    category: 'Shoes',
    subcategory: 'Sports & Fitness',
    price: 1999,
    oldPrice: 3999,
    rating: 4.7,
    reviews: 5600,
    image: img('https://images.pexels.com/photos/1456733/pexels-photo-1456733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/1456733/pexels-photo-1456733.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15475641/pexels-photo-15475641.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Professional running shoes with cushioned sole, breathable mesh upper, and lightweight design. Go the extra mile.',
    features: ['Cushioned Sole', 'Breathable Mesh', 'Lightweight', 'Anti-slip Outsole', 'Arch Support'],
    badge: 'Best Seller',
  },
  {
    id: 19,
    name: 'Stylish Sneakers',
    category: 'Shoes',
    subcategory: 'Fashion',
    price: 1599,
    oldPrice: 2999,
    rating: 4.4,
    reviews: 2800,
    image: img('https://images.pexels.com/photos/9207813/pexels-photo-9207813.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/9207813/pexels-photo-9207813.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Fashion-forward sneakers that combine style and comfort. Perfect for casual outings and streetwear.',
    features: ['Comfortable Fit', 'Durable Outsole', 'Padded Collar', 'Trendy Design', 'Multiple Sizes'],
    badge: 'Trending',
  },
  {
    id: 20,
    name: 'Athletic Sports Shoes',
    category: 'Shoes',
    subcategory: 'Sports & Fitness',
    price: 2299,
    oldPrice: 3999,
    rating: 4.5,
    reviews: 3200,
    image: img('https://images.pexels.com/photos/15475641/pexels-photo-15475641.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/15475641/pexels-photo-15475641.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'High-performance athletic shoes designed for training, running, and gym workouts. Maximum comfort and support.',
    features: ['Shock Absorption', 'Flexible Sole', 'Breathable Upper', 'Reinforced Toe', 'Sport Design'],
  },

  // Accessories
  {
    id: 21,
    name: 'Premium Leather Handbag',
    category: 'Accessories',
    subcategory: "Women's Fashion",
    price: 2499,
    oldPrice: 4999,
    rating: 4.6,
    reviews: 1450,
    image: img('https://images.pexels.com/photos/14806252/pexels-photo-14806252.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/14806252/pexels-photo-14806252.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/34316381/pexels-photo-34316381.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Elegant leather handbag with spacious compartments and premium finish. A perfect blend of style and functionality.',
    features: ['Genuine Leather', 'Spacious Interior', 'Adjustable Strap', 'Multiple Pockets', 'Premium Finish'],
    badge: 'Premium',
  },
  {
    id: 22,
    name: 'Designer Blue Handbag',
    category: 'Accessories',
    subcategory: "Women's Fashion",
    price: 1899,
    oldPrice: 3499,
    rating: 4.4,
    reviews: 980,
    image: img('https://images.pexels.com/photos/34316381/pexels-photo-34316381.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/34316381/pexels-photo-34316381.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Stylish blue handbag with elegant design and durable construction. A great accessory for any outfit.',
    features: ['Premium Material', 'Spacious Design', 'Detachable Strap', 'Magnetic Closure', 'Trendy Color'],
  },
  {
    id: 23,
    name: 'Stylish Backpack',
    category: 'Accessories',
    subcategory: 'Travel',
    price: 1499,
    oldPrice: 2799,
    rating: 4.5,
    reviews: 3200,
    image: img('https://images.pexels.com/photos/37580640/pexels-photo-37580640.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/37580640/pexels-photo-37580640.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/11463452/pexels-photo-11463452.png?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Durable and stylish backpack with laptop compartment, multiple pockets, and water-resistant fabric. Perfect for work and travel.',
    features: ['Laptop Compartment', 'Water Resistant', 'Multiple Pockets', 'Padded Straps', '30L Capacity'],
    badge: 'Deal',
  },
  {
    id: 24,
    name: 'Premium Sunglasses',
    category: 'Accessories',
    subcategory: 'Fashion',
    price: 999,
    oldPrice: 1999,
    rating: 4.5,
    reviews: 2100,
    image: img('https://images.pexels.com/photos/38922614/pexels-photo-38922614.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/38922614/pexels-photo-38922614.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'UV-protected sunglasses with polarized lenses and a trendy frame. Protect your eyes in style.',
    features: ['UV400 Protection', 'Polarized Lenses', 'Lightweight Frame', 'Scratch Resistant', 'Includes Case'],
    badge: 'Trending',
  },
  {
    id: 25,
    name: 'Classic Aviator Sunglasses',
    category: 'Accessories',
    subcategory: 'Fashion',
    price: 1299,
    oldPrice: 2499,
    rating: 4.6,
    reviews: 1800,
    image: img('https://images.pexels.com/photos/34978681/pexels-photo-34978681.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/34978681/pexels-photo-34978681.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Timeless aviator-style sunglasses with metal frame and gradient lenses. A classic accessory for any occasion.',
    features: ['Metal Frame', 'Gradient Lenses', 'UV Protection', 'Unisex Design', 'Premium Build'],
  },

  // Beauty
  {
    id: 26,
    name: 'Skincare Beauty Set',
    category: 'Beauty',
    subcategory: 'Beauty',
    price: 1599,
    oldPrice: 2999,
    rating: 4.5,
    reviews: 2700,
    image: img('https://images.pexels.com/photos/29709958/pexels-photo-29709958.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/29709958/pexels-photo-29709958.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/12969358/pexels-photo-12969358.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Complete skincare set with cleanser, toner, and moisturizer. Achieve healthy, glowing skin with this daily routine.',
    features: ['3-Step Routine', 'For All Skin Types', 'Dermatologist Tested', 'Cruelty Free', 'Natural Ingredients'],
    badge: 'Best Seller',
  },
  {
    id: 27,
    name: 'Luxury Lipstick Collection',
    category: 'Beauty',
    subcategory: 'Beauty',
    price: 899,
    oldPrice: 1799,
    rating: 4.6,
    reviews: 3400,
    image: img('https://images.pexels.com/photos/1625037/pexels-photo-1625037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/1625037/pexels-photo-1625037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Set of 4 long-lasting matte lipsticks in trending shades. Smooth application with rich color payoff.',
    features: ['Set of 4 Shades', 'Long-lasting Matte', 'Moisturizing Formula', 'Cruelty Free', 'Premium Quality'],
    badge: 'Deal',
  },
  {
    id: 28,
    name: 'Signature Perfume Eau de Parfum',
    category: 'Beauty',
    subcategory: 'Beauty',
    price: 2199,
    oldPrice: 3999,
    rating: 4.7,
    reviews: 1900,
    image: img('https://images.pexels.com/photos/21008941/pexels-photo-21008941.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/21008941/pexels-photo-21008941.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/20591858/pexels-photo-20591858.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Long-lasting eau de parfum with floral and woody notes. A sophisticated fragrance for day and evening wear.',
    features: ['50ml Bottle', 'Long-lasting Fragrance', 'Floral & Woody Notes', 'Eau de Parfum', 'Premium Packaging'],
    badge: 'Premium',
  },
  {
    id: 29,
    name: 'BB Cream Foundation',
    category: 'Beauty',
    subcategory: 'Beauty',
    price: 699,
    oldPrice: 1299,
    rating: 4.3,
    reviews: 2200,
    image: img('https://images.pexels.com/photos/13534508/pexels-photo-13534508.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/13534508/pexels-photo-13534508.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Multi-purpose BB cream that moisturizes, protects, and provides natural coverage. SPF 30 for sun protection.',
    features: ['SPF 30 Protection', 'Natural Coverage', 'Hydrating Formula', 'All Skin Types', 'Lightweight'],
  },

  // Home & Kitchen
  {
    id: 30,
    name: 'High-Speed Mixer Grinder',
    category: 'Home & Kitchen',
    subcategory: 'Home & Kitchen',
    price: 3499,
    oldPrice: 5999,
    rating: 4.4,
    reviews: 2800,
    image: img('https://images.pexels.com/photos/19599327/pexels-photo-19599327.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/19599327/pexels-photo-19599327.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30946801/pexels-photo-30946801.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Powerful 750W mixer grinder with 3 stainless steel jars. Perfect for grinding, blending, and juicing.',
    features: ['750W Motor', '3 Stainless Jars', 'Overload Protection', 'Anti-slip Feet', '2-year Warranty'],
    badge: 'Deal',
  },
  {
    id: 31,
    name: 'Retro Kitchen Appliance Set',
    category: 'Home & Kitchen',
    subcategory: 'Home & Kitchen',
    price: 5999,
    oldPrice: 8999,
    rating: 4.5,
    reviews: 1100,
    image: img('https://images.pexels.com/photos/30946798/pexels-photo-30946798.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/30946798/pexels-photo-30946798.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Stylish retro kitchen appliance set including blender, mixer, and kettle. Add charm to your kitchen.',
    features: ['3-Piece Set', 'Retro Design', 'Stainless Steel', 'Energy Efficient', 'Easy to Clean'],
  },

  // Furniture
  {
    id: 32,
    name: 'Modern Accent Chair',
    category: 'Furniture',
    subcategory: 'Furniture',
    price: 8999,
    oldPrice: 14999,
    rating: 4.5,
    reviews: 760,
    image: img('https://images.pexels.com/photos/2766975/pexels-photo-2766975.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/2766975/pexels-photo-2766975.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7670336/pexels-photo-7670336.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Contemporary accent chair with premium upholstery and sturdy wooden frame. Adds elegance to any living space.',
    features: ['Premium Upholstery', 'Solid Wood Frame', 'High-density Foam', 'Easy Assembly', 'Modern Design'],
    badge: 'Premium',
  },
  {
    id: 33,
    name: 'Minimalist White Chair',
    category: 'Furniture',
    subcategory: 'Furniture',
    price: 5999,
    oldPrice: 9999,
    rating: 4.3,
    reviews: 540,
    image: img('https://images.pexels.com/photos/32562036/pexels-photo-32562036.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/32562036/pexels-photo-32562036.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Clean, minimalist chair in soft white fabric. Perfect for modern interiors and small spaces.',
    features: ['Soft Fabric', 'Minimalist Design', 'Lightweight', 'Sturdy Build', 'Easy to Clean'],
  },

  // Home Decor
  {
    id: 34,
    name: 'Designer Table Lamp',
    category: 'Home & Kitchen',
    subcategory: 'Home & Kitchen',
    price: 1299,
    oldPrice: 2499,
    rating: 4.4,
    reviews: 1300,
    image: img('https://images.pexels.com/photos/35392792/pexels-photo-35392792.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/35392792/pexels-photo-35392792.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30877426/pexels-photo-30877426.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Elegant table lamp with warm LED light and modern design. Creates a cozy ambiance in any room.',
    features: ['LED Bulb Included', 'Warm Light', 'Adjustable Brightness', 'Modern Design', 'Energy Efficient'],
    badge: 'Trending',
  },
  {
    id: 35,
    name: 'Ceramic Vase Decor Set',
    category: 'Home & Kitchen',
    subcategory: 'Home & Kitchen',
    price: 899,
    oldPrice: 1799,
    rating: 4.5,
    reviews: 890,
    image: img('https://images.pexels.com/photos/16411135/pexels-photo-16411135.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/16411135/pexels-photo-16411135.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7119222/pexels-photo-7119222.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Set of 2 handcrafted ceramic vases with textured patterns. A beautiful addition to your home decor.',
    features: ['Set of 2 Vases', 'Handcrafted', 'Textured Design', 'Premium Ceramic', 'Versatile Decor'],
  },

  // Books
  {
    id: 36,
    name: 'Bestseller Novel Collection',
    category: 'Books',
    subcategory: 'Books',
    price: 699,
    oldPrice: 1499,
    rating: 4.8,
    reviews: 6700,
    image: img('https://images.pexels.com/photos/433333/pexels-photo-433333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/433333/pexels-photo-433333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Collection of 3 bestselling novels across fiction and self-help. Perfect for avid readers and gifting.',
    features: ['Set of 3 Books', 'Paperback Edition', 'Award Winners', 'English Language', 'Premium Print'],
    badge: 'Best Seller',
  },
  {
    id: 37,
    name: 'Knowledge Book Bundle',
    category: 'Books',
    subcategory: 'Books',
    price: 999,
    oldPrice: 1999,
    rating: 4.6,
    reviews: 2300,
    image: img('https://images.pexels.com/photos/8762862/pexels-photo-8762862.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/8762862/pexels-photo-8762862.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Curated bundle of educational and inspirational books. Expand your knowledge across multiple topics.',
    features: ['5-Book Bundle', 'Hardcover Edition', 'Educational', 'Illustrated', 'Premium Quality'],
  },

  // Sports & Fitness
  {
    id: 38,
    name: 'Adjustable Dumbbell Set',
    category: 'Sports & Fitness',
    subcategory: 'Sports & Fitness',
    price: 4999,
    oldPrice: 8999,
    rating: 4.6,
    reviews: 1900,
    image: img('https://images.pexels.com/photos/19025674/pexels-photo-19025674.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/19025674/pexels-photo-19025674.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/35567437/pexels-photo-35567437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Adjustable dumbbell set with weight range from 2kg to 20kg per hand. Perfect for home gym workouts.',
    features: ['2kg-20kg Adjustable', 'Space-saving Design', 'Anti-slip Grip', 'Durable Build', 'Storage Tray Included'],
    badge: 'Deal',
  },
  {
    id: 39,
    name: 'Professional Dumbbells Pair',
    category: 'Sports & Fitness',
    subcategory: 'Sports & Fitness',
    price: 2999,
    oldPrice: 5999,
    rating: 4.4,
    reviews: 1450,
    image: img('https://images.pexels.com/photos/35567437/pexels-photo-35567437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/35567437/pexels-photo-35567437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Pair of professional-grade dumbbells with ergonomic grip and rubber coating. Ideal for strength training.',
    features: ['Pair of Dumbbells', 'Rubber Coated', 'Ergonomic Grip', 'Rust Resistant', 'Multiple Weight Options'],
  },

  // Grocery
  {
    id: 40,
    name: 'Fresh Organic Vegetables Box',
    category: 'Grocery',
    subcategory: 'Grocery',
    price: 599,
    oldPrice: 999,
    rating: 4.3,
    reviews: 3400,
    image: img('https://images.pexels.com/photos/7129143/pexels-photo-7129143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/7129143/pexels-photo-7129143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Fresh, organic vegetables sourced directly from farms. Includes seasonal variety for healthy meals.',
    features: ['100% Organic', 'Farm Fresh', 'Seasonal Variety', 'No Pesticides', 'Same Day Delivery'],
    badge: 'Fresh',
  },
  {
    id: 41,
    name: 'Fresh Farm Produce Bundle',
    category: 'Grocery',
    subcategory: 'Grocery',
    price: 449,
    oldPrice: 799,
    rating: 4.4,
    reviews: 2100,
    image: img('https://images.pexels.com/photos/31330105/pexels-photo-31330105.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/31330105/pexels-photo-31330105.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Bundle of fresh farm produce including cucumbers, peppers, and leafy greens. Healthy eating made easy.',
    features: ['Farm Sourced', 'Pesticide Free', 'Mixed Vegetables', 'Eco Packaging', 'Quick Delivery'],
  },

  // Toys
  {
    id: 42,
    name: 'Construction Toys Set',
    category: 'Toys',
    subcategory: 'Toys',
    price: 899,
    oldPrice: 1799,
    rating: 4.5,
    reviews: 1800,
    image: img('https://images.pexels.com/photos/14007163/pexels-photo-14007163.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/14007163/pexels-photo-14007163.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Educational construction toys set with 100+ pieces. Develops creativity and problem-solving skills in kids.',
    features: ['100+ Pieces', 'Non-toxic Material', 'Age 3+', 'STEM Learning', 'Storage Box Included'],
    badge: 'Kids Choice',
  },
  {
    id: 43,
    name: 'Plush Dinosaur Toy',
    category: 'Toys',
    subcategory: 'Toys',
    price: 599,
    oldPrice: 1199,
    rating: 4.7,
    reviews: 2600,
    image: img('https://images.pexels.com/photos/6974751/pexels-photo-6974751.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/6974751/pexels-photo-6974751.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Soft and cuddly plush dinosaur toy. Perfect companion for kids. Made with child-safe materials.',
    features: ['Soft Plush', 'Child-safe', 'Machine Washable', 'Age 0+', 'Hypoallergenic'],
  },
  {
    id: 44,
    name: 'Wooden Building Blocks',
    category: 'Toys',
    subcategory: 'Toys',
    price: 749,
    oldPrice: 1499,
    rating: 4.6,
    reviews: 1500,
    image: img('https://images.pexels.com/photos/3661452/pexels-photo-3661452.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/3661452/pexels-photo-3661452.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Classic wooden building blocks set with 60 colorful pieces. Enhances motor skills and creativity.',
    features: ['60 Wooden Blocks', 'Non-toxic Paint', 'Age 2+', 'Storage Bag', 'Educational Toy'],
  },

  // Travel
  {
    id: 45,
    name: 'Premium Travel Suitcase',
    category: 'Travel',
    subcategory: 'Travel',
    price: 4999,
    oldPrice: 8999,
    rating: 4.5,
    reviews: 1200,
    image: img('https://images.pexels.com/photos/27945494/pexels-photo-27945494.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/27945494/pexels-photo-27945494.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Durable hard-shell suitcase with 360-degree spinner wheels and TSA-approved lock. Travel in style and security.',
    features: ['Hard Shell', '4 Spinner Wheels', 'TSA Lock', '28-inch Size', '10-year Warranty'],
    badge: 'Premium',
  },
  {
    id: 46,
    name: 'Cabin Travel Bag',
    category: 'Travel',
    subcategory: 'Travel',
    price: 1999,
    oldPrice: 3999,
    rating: 4.4,
    reviews: 890,
    image: img('https://images.pexels.com/photos/5138184/pexels-photo-5138184.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
    images: [
      'https://images.pexels.com/photos/5138184/pexels-photo-5138184.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    description: 'Compact cabin-size travel bag with multiple compartments and lightweight design. Perfect for short trips.',
    features: ['Cabin Size', 'Lightweight', 'Multiple Compartments', 'Water Resistant', 'Trolley Strap'],
  },
]

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'All') return products
  return products.filter(
    (p) => p.category === category || p.subcategory === category
  )
}

export function searchProducts(query: string): Product[] {
  const words = query.toLowerCase().split(' ').filter((w) => w.length > 0)
  if (words.length === 0) return products
  return products.filter((p) => {
    const text = `${p.name} ${p.category} ${p.subcategory} ${p.description}`.toLowerCase()
    return words.some((w) => text.includes(w))
  })
}

export function getDiscountPercent(price: number, oldPrice: number): number {
  return Math.round(((oldPrice - price) / oldPrice) * 100)
}
